services:
  - type: web
    name: inreach-backend
    env: node
    rootDir: apps/backend
    buildCommand: npm install && npm run build
    startCommand: node dist/index.js
    envVars:
      - key: API_KEY_OPENAI
        sync: false
      - key: API_KEY_SUPABASE
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: LANGSMITH_TRACING
        sync: false
      - key: LANGSMITH_ENDPOINT
        sync: false
      - key: LANGSMITH_API_KEY
        sync: false
      - key: LANGSMITH_PROJECT
        sync: false
      - key: SNOV_CLIENT_ID
        sync: false
      - key: SNOV_CLIENT_SECRET
        sync: false
      - key: ANTHROPIC_API_KEY
        sync: false
    runtime: node
